### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by ChangpeiHe** [DHI-GRAS/creodias-finder#10]
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
  File "/storage2/home/co2group/anaconda3/lib/python3.8/site-packages/creodias_finder-0.1.0-py3.8.egg/creodias_finder/download.py", line 45, in download
  File "/storage2/home/co2group/anaconda3/lib/python3.8/site-packages/creodias_finder-0.1.0-py3.8.egg/creodias_finder/download.py", line 154, in _download_raw_data
FileNotFoundError: [Errno 2] No such file or directory: '/storage2/home/co2group/Sentinel-3/file.zip.incomplete'

**Comment by j08lue** [comment]
I guess the parent directory `/storage2/home/co2group/Sentinel-3` did not exist.

Create it in your code with

```python
from pathlib import Path

target_path = Path("storage2/home/co2group/Sentinel-3/file.zip")
target_path.parent.mkdir(parents=True, exist_ok=True)
```

**Comment by ChangpeiHe** [comment]
> I guess the parent directory `/storage2/home/co2group/Sentinel-3` did not exist.
> 
> Create it in your code with
> 
> ```python
> from pathlib import Path
> 
> target_path = Path("storage2/home/co2group/Sentinel-3/file.zip")
> target_path.parent.mkdir(parents=True, exist_ok=True)
> ```

Thanks
